import type { EnemyVariant } from '../types/GameTypes';

export const ENEMY_VARIANTS: EnemyVariant[] = [
  { id: 'ember-imp', name: 'Ember Imp', bodyColor: 0xff6b35, accentColor: 0xffc857, coreColor: 0x3b1022, shape: 'horn', hpScale: 0.9, radius: 18, damage: 1, imageKey: 'enemyStrawberryImp' },
  { id: 'frost-wisp', name: 'Frost Wisp', bodyColor: 0x7dd3fc, accentColor: 0xe0f2fe, coreColor: 0x0f172a, shape: 'wisp', hpScale: 0.85, radius: 17, damage: 1, imageKey: 'enemyFrostLens' },
  { id: 'thorn-beast', name: 'Thorn Beast', bodyColor: 0x22c55e, accentColor: 0xbbf7d0, coreColor: 0x052e16, shape: 'horn', hpScale: 1.05, radius: 19, damage: 1 },
  { id: 'violet-eye', name: 'Violet Eye', bodyColor: 0xa855f7, accentColor: 0xf0abfc, coreColor: 0x1e103a, shape: 'orb', hpScale: 0.95, radius: 18, damage: 1 },
  { id: 'iron-golem', name: 'Iron Golem', bodyColor: 0x94a3b8, accentColor: 0xf8fafc, coreColor: 0x1e293b, shape: 'golem', hpScale: 1.35, radius: 21, damage: 1 },
  { id: 'shadow-mask', name: 'Shadow Mask', bodyColor: 0x4338ca, accentColor: 0xc4b5fd, coreColor: 0x020617, shape: 'mask', hpScale: 1.1, radius: 19, damage: 1 },
  { id: 'solar-mite', name: 'Solar Mite', bodyColor: 0xfacc15, accentColor: 0xffedd5, coreColor: 0x451a03, shape: 'wing', hpScale: 0.8, radius: 17, damage: 1 },
  { id: 'moon-slime', name: 'Moon Slime', bodyColor: 0x67e8f9, accentColor: 0xd8b4fe, coreColor: 0x083344, shape: 'slime', hpScale: 0.9, radius: 18, damage: 1 },
  { id: 'ruby-wyrm', name: 'Ruby Wyrm', bodyColor: 0xf43f5e, accentColor: 0xfda4af, coreColor: 0x450a0a, shape: 'wyrm', hpScale: 1.25, radius: 20, damage: 1 },
  { id: 'jade-wyrm', name: 'Jade Wyrm', bodyColor: 0x10b981, accentColor: 0xa7f3d0, coreColor: 0x064e3b, shape: 'wyrm', hpScale: 1.2, radius: 20, damage: 1 },
  { id: 'storm-bat', name: 'Storm Bat', bodyColor: 0x38bdf8, accentColor: 0xfef08a, coreColor: 0x0c4a6e, shape: 'wing', hpScale: 0.95, radius: 18, damage: 1 },
  { id: 'ash-orb', name: 'Ash Orb', bodyColor: 0x64748b, accentColor: 0xfb7185, coreColor: 0x111827, shape: 'orb', hpScale: 1.0, radius: 18, damage: 1 },
  { id: 'glass-golem', name: 'Glass Golem', bodyColor: 0x99f6e4, accentColor: 0x5eead4, coreColor: 0x134e4a, shape: 'golem', hpScale: 1.4, radius: 22, damage: 1 },
  { id: 'dream-wisp', name: 'Dream Wisp', bodyColor: 0xf0abfc, accentColor: 0xbfdbfe, coreColor: 0x581c87, shape: 'wisp', hpScale: 0.88, radius: 17, damage: 1 },
  { id: 'lava-slime', name: 'Lava Slime', bodyColor: 0xfb923c, accentColor: 0xfef3c7, coreColor: 0x7c2d12, shape: 'slime', hpScale: 1.05, radius: 19, damage: 1 },
  { id: 'bone-mask', name: 'Bone Mask', bodyColor: 0xf5f5f4, accentColor: 0xfca5a5, coreColor: 0x292524, shape: 'mask', hpScale: 1.15, radius: 19, damage: 1 },
  { id: 'azure-imp', name: 'Azure Imp', bodyColor: 0x2563eb, accentColor: 0x93c5fd, coreColor: 0x172554, shape: 'horn', hpScale: 1.0, radius: 18, damage: 1 },
  { id: 'golden-eye', name: 'Golden Eye', bodyColor: 0xeab308, accentColor: 0xfef08a, coreColor: 0x422006, shape: 'orb', hpScale: 1.08, radius: 18, damage: 1 },
  { id: 'void-wyrm', name: 'Void Wyrm', bodyColor: 0x312e81, accentColor: 0xa78bfa, coreColor: 0x030712, shape: 'wyrm', hpScale: 1.45, radius: 22, damage: 1 },
  { id: 'mist-horn', name: 'Mist Horn', bodyColor: 0xbae6fd, accentColor: 0xf8fafc, coreColor: 0x075985, shape: 'horn', hpScale: 0.92, radius: 18, damage: 1 },
  { id: 'neon-slime', name: 'Neon Slime', bodyColor: 0x2dd4bf, accentColor: 0xf0fdfa, coreColor: 0x042f2e, shape: 'slime', hpScale: 0.98, radius: 18, damage: 1 },
  { id: 'scarlet-bat', name: 'Scarlet Bat', bodyColor: 0xe11d48, accentColor: 0xfda4af, coreColor: 0x4c0519, shape: 'wing', hpScale: 1.0, radius: 18, damage: 1 },
  { id: 'opal-mask', name: 'Opal Mask', bodyColor: 0xc4b5fd, accentColor: 0x99f6e4, coreColor: 0x2e1065, shape: 'mask', hpScale: 1.22, radius: 20, damage: 1 },
  { id: 'cinder-golem', name: 'Cinder Golem', bodyColor: 0x9a3412, accentColor: 0xfdba74, coreColor: 0x1c1917, shape: 'golem', hpScale: 1.5, radius: 23, damage: 1 },
  { id: 'doom-reaper', name: 'Doom Reaper', bodyColor: 0x020617, accentColor: 0xff174d, coreColor: 0xffffff, shape: 'mask', hpScale: 2.8, radius: 24, damage: 99, lethal: true },
  { id: 'red-comet', name: 'Red Comet', bodyColor: 0xff174d, accentColor: 0xfef2f2, coreColor: 0x450a0a, shape: 'wyrm', hpScale: 2.1, radius: 22, damage: 2 },
  { id: 'void-gatekeeper', name: 'Void Gatekeeper', bodyColor: 0x111827, accentColor: 0xa855f7, coreColor: 0xf8fafc, shape: 'golem', hpScale: 3.2, radius: 25, damage: 3 },
  { id: 'sand-skull', name: 'Sand Skull', bodyColor: 0xd6a65a, accentColor: 0xffedd5, coreColor: 0x451a03, shape: 'mask', hpScale: 1.05, radius: 18, damage: 1 },
  { id: 'blue-ogre', name: 'Blue Ogre', bodyColor: 0x3b82f6, accentColor: 0xbfdbfe, coreColor: 0x172554, shape: 'golem', hpScale: 1.65, radius: 22, damage: 2 },
  { id: 'pink-harpy', name: 'Pink Harpy', bodyColor: 0xf472b6, accentColor: 0xfbcfe8, coreColor: 0x831843, shape: 'wing', hpScale: 1.0, radius: 18, damage: 1 },
  { id: 'green-goblin', name: 'Green Goblin', bodyColor: 0x84cc16, accentColor: 0xecfccb, coreColor: 0x365314, shape: 'beast', hpScale: 0.95, radius: 17, damage: 1 },
  { id: 'silver-knight', name: 'Silver Knight', bodyColor: 0xcbd5e1, accentColor: 0xffffff, coreColor: 0x334155, shape: 'knight', hpScale: 1.75, radius: 22, damage: 2 },
  { id: 'pumpkin-hex', name: 'Pumpkin Hex', bodyColor: 0xf97316, accentColor: 0xfef08a, coreColor: 0x431407, shape: 'plant', hpScale: 1.05, radius: 19, damage: 1 },
  { id: 'aqua-siren', name: 'Aqua Siren', bodyColor: 0x06b6d4, accentColor: 0xccfbf1, coreColor: 0x164e63, shape: 'wisp', hpScale: 1.0, radius: 18, damage: 1 },
  { id: 'grave-crow', name: 'Grave Crow', bodyColor: 0x1f2937, accentColor: 0x9ca3af, coreColor: 0x030712, shape: 'wing', hpScale: 1.1, radius: 19, damage: 2 },
  { id: 'scarab-guard', name: 'Scarab Guard', bodyColor: 0x0f766e, accentColor: 0x5eead4, coreColor: 0x042f2e, shape: 'spider', hpScale: 1.6, radius: 21, damage: 2, imageKey: 'enemyBrassBeetle' },
  { id: 'ruby-mimic', name: 'Ruby Mimic', bodyColor: 0xbe123c, accentColor: 0xfda4af, coreColor: 0x4c0519, shape: 'mask', hpScale: 1.2, radius: 19, damage: 1 },
  { id: 'snow-yeti', name: 'Snow Yeti', bodyColor: 0xe0f2fe, accentColor: 0x7dd3fc, coreColor: 0x075985, shape: 'beast', hpScale: 1.8, radius: 23, damage: 2 },
  { id: 'thunder-ram', name: 'Thunder Ram', bodyColor: 0xfacc15, accentColor: 0xfef9c3, coreColor: 0x713f12, shape: 'horn', hpScale: 1.3, radius: 20, damage: 2 },
  { id: 'violet-moth', name: 'Violet Moth', bodyColor: 0x9333ea, accentColor: 0xe9d5ff, coreColor: 0x3b0764, shape: 'wing', hpScale: 0.95, radius: 18, damage: 1, imageKey: 'enemyVioletMoth' },
  { id: 'mud-brute', name: 'Mud Brute', bodyColor: 0x78350f, accentColor: 0xfbbf24, coreColor: 0x1c1917, shape: 'beast', hpScale: 1.7, radius: 23, damage: 2 },
  { id: 'necro-eye', name: 'Necro Eye', bodyColor: 0x4c1d95, accentColor: 0xf0abfc, coreColor: 0x020617, shape: 'orb', hpScale: 1.25, radius: 19, damage: 2 },
  { id: 'coral-slime', name: 'Coral Slime', bodyColor: 0xfb7185, accentColor: 0xffedd5, coreColor: 0x881337, shape: 'slime', hpScale: 1.0, radius: 18, damage: 1 },
  { id: 'iron-wyvern', name: 'Iron Wyvern', bodyColor: 0x475569, accentColor: 0xe2e8f0, coreColor: 0x0f172a, shape: 'wyrm', hpScale: 1.75, radius: 23, damage: 2 },
  { id: 'mint-ghost', name: 'Mint Ghost', bodyColor: 0xa7f3d0, accentColor: 0xf0fdfa, coreColor: 0x064e3b, shape: 'wisp', hpScale: 0.9, radius: 17, damage: 1 },
  { id: 'blood-idol', name: 'Blood Idol', bodyColor: 0x991b1b, accentColor: 0xfca5a5, coreColor: 0x450a0a, shape: 'mask', hpScale: 1.45, radius: 20, damage: 2 },
  { id: 'cosmo-jelly', name: 'Cosmo Jelly', bodyColor: 0x6366f1, accentColor: 0xc4b5fd, coreColor: 0x1e1b4b, shape: 'slime', hpScale: 1.08, radius: 19, damage: 1 },
  { id: 'sun-lion', name: 'Sun Lion', bodyColor: 0xf59e0b, accentColor: 0xfef3c7, coreColor: 0x7c2d12, shape: 'beast', hpScale: 1.5, radius: 21, damage: 2 },
  { id: 'toxic-vial', name: 'Toxic Vial', bodyColor: 0x84cc16, accentColor: 0xd9f99d, coreColor: 0x1a2e05, shape: 'slime', hpScale: 1.35, radius: 20, damage: 1, imageKey: 'enemyToxicVial', statusEffect: 'poison', statusChance: 0.9 },
  { id: 'shock-coil', name: 'Shock Coil', bodyColor: 0xfacc15, accentColor: 0x38bdf8, coreColor: 0x422006, shape: 'spider', hpScale: 1.28, radius: 20, damage: 1, imageKey: 'enemyShockCoil', statusEffect: 'paralyze', statusChance: 0.85 },
  { id: 'hex-mirror', name: 'Hex Mirror', bodyColor: 0x18181b, accentColor: 0xc084fc, coreColor: 0xf0abfc, shape: 'mask', hpScale: 2.05, radius: 22, damage: 2, imageKey: 'enemyHexMirror', statusEffect: 'curse', statusChance: 0.75 },
  { id: 'frost-chain', name: 'Frost Chain', bodyColor: 0xbfdbfe, accentColor: 0xf8fafc, coreColor: 0x1d4ed8, shape: 'knight', hpScale: 1.9, radius: 22, damage: 2, imageKey: 'enemyFrostChain', statusEffect: 'freeze', statusChance: 0.8 },
  { id: 'rust-bomb', name: 'Rust Bomb', bodyColor: 0x7c2d12, accentColor: 0xfdba74, coreColor: 0x1c1917, shape: 'golem', hpScale: 2.45, radius: 25, damage: 3, imageKey: 'enemyRustBomb', statusEffect: 'burn', statusChance: 0.72 },
  { id: 'neon-razor', name: 'Neon Razor', bodyColor: 0x06b6d4, accentColor: 0xf0abfc, coreColor: 0x164e63, shape: 'wing', hpScale: 0.72, radius: 18, damage: 1, imageKey: 'enemyNeonRazor', statusEffect: 'paralyze', statusChance: 0.45 },
  { id: 'prism-jaw', name: 'Prism Jaw', bodyColor: 0x99f6e4, accentColor: 0xf0abfc, coreColor: 0x0c4a6e, shape: 'orb', hpScale: 1.4, radius: 20, damage: 2, imageKey: 'enemyPrismJaw', statusEffect: 'curse', statusChance: 0.4 },
  { id: 'jet-needle', name: 'Jet Needle', bodyColor: 0x60a5fa, accentColor: 0xe0f2fe, coreColor: 0x1d4ed8, shape: 'wing', hpScale: 0.82, radius: 18, damage: 1, imageKey: 'enemyJetNeedle', statusEffect: 'freeze', statusChance: 0.35 },
  { id: 'amber-gear', name: 'Amber Gear', bodyColor: 0xb45309, accentColor: 0xfde68a, coreColor: 0x451a03, shape: 'golem', hpScale: 1.85, radius: 22, damage: 2, imageKey: 'enemyAmberGear', statusEffect: 'paralyze', statusChance: 0.42 },
  { id: 'crimson-shell', name: 'Crimson Shell', bodyColor: 0xbe123c, accentColor: 0xfca5a5, coreColor: 0x4c0519, shape: 'spider', hpScale: 1.65, radius: 21, damage: 2, imageKey: 'enemyCrimsonShell', statusEffect: 'burn', statusChance: 0.5 },
  { id: 'nightmare-bat', name: 'Nightmare Bat', bodyColor: 0x581c87, accentColor: 0xf0abfc, coreColor: 0x030712, shape: 'wing', hpScale: 1.25, radius: 20, damage: 2 },
  { id: 'plague-orb', name: 'Plague Orb', bodyColor: 0x65a30d, accentColor: 0xd9f99d, coreColor: 0x1a2e05, shape: 'orb', hpScale: 1.2, radius: 19, damage: 2 },
  { id: 'brass-golem', name: 'Brass Golem', bodyColor: 0xb45309, accentColor: 0xfde68a, coreColor: 0x451a03, shape: 'golem', hpScale: 1.9, radius: 24, damage: 2 },
  { id: 'white-serpent', name: 'White Serpent', bodyColor: 0xf8fafc, accentColor: 0xbae6fd, coreColor: 0x0c4a6e, shape: 'wyrm', hpScale: 1.35, radius: 21, damage: 1 },
  { id: 'rose-mirror', name: 'Rose Mirror', bodyColor: 0xf9a8d4, accentColor: 0xffffff, coreColor: 0x831843, shape: 'mask', hpScale: 1.18, radius: 19, damage: 1 },
  { id: 'electric-urchin', name: 'Electric Urchin', bodyColor: 0xfef08a, accentColor: 0x38bdf8, coreColor: 0x713f12, shape: 'spider', hpScale: 1.08, radius: 18, damage: 2 },
  { id: 'obsidian-hulk', name: 'Obsidian Hulk', bodyColor: 0x27272a, accentColor: 0xa1a1aa, coreColor: 0x000000, shape: 'golem', hpScale: 2.1, radius: 25, damage: 3 },
  { id: 'sky-lancer', name: 'Sky Lancer', bodyColor: 0x60a5fa, accentColor: 0xf0f9ff, coreColor: 0x1d4ed8, shape: 'knight', hpScale: 1.22, radius: 19, damage: 1 },
  { id: 'crimson-head', name: 'Crimson Head', bodyColor: 0xef4444, accentColor: 0xffedd5, coreColor: 0x7f1d1d, shape: 'horn', hpScale: 1.55, radius: 22, damage: 3 },
  { id: 'ancient-core', name: 'Ancient Core', bodyColor: 0x14b8a6, accentColor: 0xccfbf1, coreColor: 0x134e4a, shape: 'orb', hpScale: 1.7, radius: 22, damage: 2 },
  { id: 'gold-reaper', name: 'Gold Reaper', bodyColor: 0x451a03, accentColor: 0xfacc15, coreColor: 0xffffff, shape: 'mask', hpScale: 3.1, radius: 25, damage: 99, lethal: true },
  { id: 'black-meteor', name: 'Black Meteor', bodyColor: 0x030712, accentColor: 0xfb7185, coreColor: 0xf8fafc, shape: 'wyrm', hpScale: 2.35, radius: 24, damage: 3 },
  { id: 'mirror-fiend', name: 'Mirror Fiend', bodyColor: 0xe0e7ff, accentColor: 0x818cf8, coreColor: 0x312e81, shape: 'mask', hpScale: 1.42, radius: 20, damage: 2 },
  { id: 'frost-knight', name: 'Frost Knight', bodyColor: 0xbfdbfe, accentColor: 0xf8fafc, coreColor: 0x1d4ed8, shape: 'knight', hpScale: 1.82, radius: 22, damage: 2 },
  { id: 'plasma-mantis', name: 'Plasma Mantis', bodyColor: 0x22d3ee, accentColor: 0xf0fdfa, coreColor: 0x164e63, shape: 'spider', hpScale: 1.28, radius: 20, damage: 2 },
  { id: 'ember-lion', name: 'Ember Lion', bodyColor: 0xf97316, accentColor: 0xfef3c7, coreColor: 0x7c2d12, shape: 'beast', hpScale: 1.58, radius: 22, damage: 2 },
  { id: 'void-stalker', name: 'Void Stalker', bodyColor: 0x312e81, accentColor: 0xc084fc, coreColor: 0x020617, shape: 'beast', hpScale: 1.72, radius: 23, damage: 3 },
  { id: 'crystal-bloom', name: 'Crystal Bloom', bodyColor: 0x99f6e4, accentColor: 0xf0abfc, coreColor: 0x134e4a, shape: 'plant', hpScale: 1.34, radius: 20, damage: 1 },
  { id: 'golden-paladin', name: 'Golden Paladin', bodyColor: 0xfacc15, accentColor: 0xffffff, coreColor: 0x713f12, shape: 'knight', hpScale: 2.05, radius: 24, damage: 3 },
  { id: 'nebula-wisp', name: 'Nebula Wisp', bodyColor: 0x7c3aed, accentColor: 0x67e8f9, coreColor: 0x020617, shape: 'wisp', hpScale: 1.18, radius: 19, damage: 2 },
  { id: 'toxic-vine', name: 'Toxic Vine', bodyColor: 0x65a30d, accentColor: 0xd9f99d, coreColor: 0x1a2e05, shape: 'plant', hpScale: 1.46, radius: 21, damage: 2 },
  { id: 'scarlet-lancer', name: 'Scarlet Lancer', bodyColor: 0xdc2626, accentColor: 0xfecaca, coreColor: 0x450a0a, shape: 'knight', hpScale: 1.65, radius: 21, damage: 3 },
  { id: 'star-scorpion', name: 'Star Scorpion', bodyColor: 0x1e3a8a, accentColor: 0xfef08a, coreColor: 0x0f172a, shape: 'spider', hpScale: 1.7, radius: 23, damage: 3 },
  { id: 'aurora-harpy', name: 'Aurora Harpy', bodyColor: 0x5eead4, accentColor: 0xe9d5ff, coreColor: 0x0f766e, shape: 'wing', hpScale: 1.22, radius: 19, damage: 1 },
  { id: 'onyx-idol', name: 'Onyx Idol', bodyColor: 0x18181b, accentColor: 0xa1a1aa, coreColor: 0xfb7185, shape: 'mask', hpScale: 1.92, radius: 23, damage: 2 },
  { id: 'strawberry-guard', name: 'Strawberry Guard', bodyColor: 0xe11d48, accentColor: 0x86efac, coreColor: 0x4c0519, shape: 'plant', hpScale: 1.55, radius: 21, damage: 2, imageKey: 'enemyStrawberryImp', statusEffect: 'burn', statusChance: 0.32 },
  { id: 'lunar-fang', name: 'Lunar Fang', bodyColor: 0xc084fc, accentColor: 0xe0e7ff, coreColor: 0x12071f, shape: 'beast', hpScale: 1.78, radius: 23, damage: 3, imageKey: 'enemyHexMirror', statusEffect: 'curse', statusChance: 0.38 },
  { id: 'gear-octopus', name: 'Gear Octopus', bodyColor: 0xb45309, accentColor: 0xfde68a, coreColor: 0x451a03, shape: 'spider', hpScale: 1.95, radius: 24, damage: 2, imageKey: 'enemyAmberGear', statusEffect: 'paralyze', statusChance: 0.45 },
  { id: 'phoenix-spark', name: 'Phoenix Spark', bodyColor: 0xfb7185, accentColor: 0xfacc15, coreColor: 0x7f1d1d, shape: 'wing', hpScale: 1.1, radius: 19, damage: 2, imageKey: 'enemyNeonRazor', statusEffect: 'burn', statusChance: 0.4 },
  { id: 'crystal-warden', name: 'Crystal Warden', bodyColor: 0x99f6e4, accentColor: 0xf0abfc, coreColor: 0x134e4a, shape: 'knight', hpScale: 2.15, radius: 24, damage: 3, imageKey: 'enemyFrostChain', statusEffect: 'freeze', statusChance: 0.35 },
  { id: 'berry-lancer', name: 'Berry Lancer', bodyColor: 0xbe123c, accentColor: 0xffedd5, coreColor: 0x4c0519, shape: 'knight', hpScale: 1.38, radius: 20, damage: 2, imageKey: 'enemyStrawberryImp' },
  { id: 'aurora-mirror', name: 'Aurora Mirror', bodyColor: 0xa5f3fc, accentColor: 0xf0abfc, coreColor: 0x164e63, shape: 'mask', hpScale: 1.62, radius: 21, damage: 2, imageKey: 'enemyHexMirror', statusEffect: 'freeze', statusChance: 0.28 },
  { id: 'voltage-idol', name: 'Voltage Idol', bodyColor: 0xfef08a, accentColor: 0x38bdf8, coreColor: 0x422006, shape: 'orb', hpScale: 1.3, radius: 20, damage: 2, imageKey: 'enemyShockCoil', statusEffect: 'paralyze', statusChance: 0.36 },
  { id: 'rust-knight', name: 'Rust Knight', bodyColor: 0x92400e, accentColor: 0xfdba74, coreColor: 0x1c1917, shape: 'knight', hpScale: 2.05, radius: 24, damage: 3, imageKey: 'enemyRustBomb', statusEffect: 'burn', statusChance: 0.3 },
  { id: 'prism-serpent', name: 'Prism Serpent', bodyColor: 0x67e8f9, accentColor: 0xf0abfc, coreColor: 0x1e1b4b, shape: 'wyrm', hpScale: 1.52, radius: 22, damage: 2, imageKey: 'enemyPrismJaw' },
  { id: 'needle-ace', name: 'Needle Ace', bodyColor: 0x2563eb, accentColor: 0xe0f2fe, coreColor: 0x172554, shape: 'wing', hpScale: 0.78, radius: 18, damage: 2, imageKey: 'enemyJetNeedle', statusEffect: 'freeze', statusChance: 0.26 },
  { id: 'toxic-crown', name: 'Toxic Crown', bodyColor: 0x65a30d, accentColor: 0xfef08a, coreColor: 0x1a2e05, shape: 'plant', hpScale: 1.7, radius: 22, damage: 2, imageKey: 'enemyToxicVial', statusEffect: 'poison', statusChance: 0.48 },
  { id: 'crimson-crawler', name: 'Crimson Crawler', bodyColor: 0x9f1239, accentColor: 0xfca5a5, coreColor: 0x4c0519, shape: 'spider', hpScale: 1.86, radius: 23, damage: 3, imageKey: 'enemyCrimsonShell', statusEffect: 'burn', statusChance: 0.34 },
  { id: 'brass-oracle', name: 'Brass Oracle', bodyColor: 0xb45309, accentColor: 0xfef3c7, coreColor: 0x451a03, shape: 'wisp', hpScale: 1.42, radius: 20, damage: 2, imageKey: 'enemyAmberGear', statusEffect: 'curse', statusChance: 0.24 },
  { id: 'void-lantern', name: 'Void Lantern', bodyColor: 0x312e81, accentColor: 0xc4b5fd, coreColor: 0x020617, shape: 'orb', hpScale: 1.64, radius: 21, damage: 3, imageKey: 'enemyVioletMoth', statusEffect: 'curse', statusChance: 0.32 },
  { id: 'frost-saw', name: 'Frost Saw', bodyColor: 0xbfdbfe, accentColor: 0xffffff, coreColor: 0x075985, shape: 'spider', hpScale: 1.74, radius: 22, damage: 2, imageKey: 'enemyFrostChain', statusEffect: 'freeze', statusChance: 0.4 },
  { id: 'meteor-brute', name: 'Meteor Brute', bodyColor: 0x7f1d1d, accentColor: 0xfb923c, coreColor: 0x111827, shape: 'golem', hpScale: 2.38, radius: 25, damage: 4, imageKey: 'enemyRustBomb', statusEffect: 'burn', statusChance: 0.22 },
  { id: 'mint-needle', name: 'Mint Needle', bodyColor: 0x5eead4, accentColor: 0xf0fdfa, coreColor: 0x134e4a, shape: 'horn', hpScale: 1.12, radius: 19, damage: 1, imageKey: 'enemyJetNeedle' },
  { id: 'shadow-choir', name: 'Shadow Choir', bodyColor: 0x18181b, accentColor: 0xf0abfc, coreColor: 0xffffff, shape: 'wisp', hpScale: 1.58, radius: 21, damage: 2, imageKey: 'enemyHexMirror', statusEffect: 'curse', statusChance: 0.42 },
  { id: 'golden-shell', name: 'Golden Shell', bodyColor: 0xfacc15, accentColor: 0xffffff, coreColor: 0x713f12, shape: 'spider', hpScale: 2.0, radius: 24, damage: 3, imageKey: 'enemyBrassBeetle' },
  { id: 'neon-phantom', name: 'Neon Phantom', bodyColor: 0x06b6d4, accentColor: 0xf0abfc, coreColor: 0x020617, shape: 'mask', hpScale: 1.32, radius: 20, damage: 2, imageKey: 'enemyNeonRazor', statusEffect: 'paralyze', statusChance: 0.3 },
  { id: 'photo-berry-brute', name: 'Photo Berry Brute', bodyColor: 0xe11d48, accentColor: 0x86efac, coreColor: 0x4c0519, shape: 'beast', hpScale: 2.15, radius: 24, damage: 3, imageKey: 'enemyBerryBrutePhoto', statusEffect: 'burn', statusChance: 0.44 },
  { id: 'photo-crystal-lens', name: 'Photo Crystal Lens', bodyColor: 0x7dd3fc, accentColor: 0xfef08a, coreColor: 0x075985, shape: 'orb', hpScale: 1.78, radius: 23, damage: 2, imageKey: 'enemyCrystalLensPhoto', statusEffect: 'freeze', statusChance: 0.58 },
  { id: 'photo-gold-scarab', name: 'Photo Gold Scarab', bodyColor: 0xb45309, accentColor: 0xfde68a, coreColor: 0x451a03, shape: 'spider', hpScale: 2.55, radius: 25, damage: 4, imageKey: 'enemyGoldScarabPhoto', statusEffect: 'paralyze', statusChance: 0.48 },
  { id: 'photo-violet-stinger', name: 'Photo Violet Stinger', bodyColor: 0x7c3aed, accentColor: 0xf0abfc, coreColor: 0x030712, shape: 'wing', hpScale: 1.48, radius: 22, damage: 3, imageKey: 'enemyVioletStingerPhoto', statusEffect: 'curse', statusChance: 0.52 },
  { id: 'photo-chrome-mantis', name: 'Photo Chrome Mantis', bodyColor: 0xef4444, accentColor: 0xe5e7eb, coreColor: 0x111827, shape: 'spider', hpScale: 2.85, radius: 26, damage: 4, imageKey: 'enemyChromeBerryMantisPhoto', statusEffect: 'poison', statusChance: 0.5 },
  { id: 'photo-candy-core-drone', name: 'Photo Candy Core Drone', bodyColor: 0xe11d48, accentColor: 0x38bdf8, coreColor: 0x020617, shape: 'orb', hpScale: 1.42, radius: 21, damage: 2, imageKey: 'enemyCandyCoreDronePhoto', statusEffect: 'burn', statusChance: 0.36 },
  { id: 'photo-ruby-fork-drone', name: 'Photo Ruby Fork Drone', bodyColor: 0xbe123c, accentColor: 0xe5e7eb, coreColor: 0x111827, shape: 'wing', hpScale: 1.35, radius: 21, damage: 2, imageKey: 'enemyRubyForkDronePhoto', statusEffect: 'paralyze', statusChance: 0.3 },
  { id: 'photo-ice-spoon-harrier', name: 'Photo Ice Spoon Harrier', bodyColor: 0x7dd3fc, accentColor: 0xe0f2fe, coreColor: 0x075985, shape: 'wing', hpScale: 1.55, radius: 22, damage: 2, imageKey: 'enemyIceSpoonHarrierPhoto', statusEffect: 'freeze', statusChance: 0.46 },
  { id: 'photo-pepper-gear-idol', name: 'Photo Pepper Gear Idol', bodyColor: 0x22c55e, accentColor: 0xf97316, coreColor: 0x052e16, shape: 'golem', hpScale: 2.05, radius: 24, damage: 3, imageKey: 'enemyPepperGearIdolPhoto', statusEffect: 'poison', statusChance: 0.42 },
  { id: 'photo-berry-drone', name: 'Photo Berry Drone', bodyColor: 0xe11d48, accentColor: 0x38bdf8, coreColor: 0x4c0519, shape: 'orb', hpScale: 1.28, radius: 21, damage: 2, imageKey: 'enemyBerryDronePhoto', statusEffect: 'burn', statusChance: 0.34 },
  { id: 'photo-ice-lens', name: 'Photo Ice Lens', bodyColor: 0x7dd3fc, accentColor: 0xf8fafc, coreColor: 0x075985, shape: 'orb', hpScale: 1.46, radius: 22, damage: 2, imageKey: 'enemyIceLensPhoto', statusEffect: 'freeze', statusChance: 0.44 },
  { id: 'photo-brass-scarab', name: 'Photo Brass Scarab', bodyColor: 0xb45309, accentColor: 0xfde68a, coreColor: 0x451a03, shape: 'spider', hpScale: 1.82, radius: 23, damage: 3, imageKey: 'enemyBrassScarabPhoto', statusEffect: 'paralyze', statusChance: 0.26 },
  { id: 'photo-toxic-vial', name: 'Photo Toxic Vial', bodyColor: 0x84cc16, accentColor: 0xfef08a, coreColor: 0x1a2e05, shape: 'slime', hpScale: 1.58, radius: 22, damage: 2, imageKey: 'enemyToxicVialPhoto', statusEffect: 'poison', statusChance: 0.62 },
  { id: 'photo-neon-razor', name: 'Photo Neon Razor', bodyColor: 0x06b6d4, accentColor: 0xf0abfc, coreColor: 0x164e63, shape: 'wing', hpScale: 0.92, radius: 19, damage: 2, imageKey: 'enemyNeonRazorPhoto', statusEffect: 'paralyze', statusChance: 0.38 },
  { id: 'photo-hex-mirror', name: 'Photo Hex Mirror', bodyColor: 0x18181b, accentColor: 0xc084fc, coreColor: 0xf0abfc, shape: 'mask', hpScale: 1.9, radius: 23, damage: 3, imageKey: 'enemyHexMirrorPhoto', statusEffect: 'curse', statusChance: 0.52 },
  { id: 'photo-strawberry-blade-drone', name: 'Photo Strawberry Blade Drone', bodyColor: 0xe11d48, accentColor: 0x38bdf8, coreColor: 0x4c0519, shape: 'wing', hpScale: 1.24, radius: 21, damage: 2, imageKey: 'enemyStrawberryBladeDronePhoto', statusEffect: 'burn', statusChance: 0.45 },
  { id: 'photo-lemon-shock-turret', name: 'Photo Lemon Shock Turret', bodyColor: 0xfacc15, accentColor: 0x38bdf8, coreColor: 0x422006, shape: 'spider', hpScale: 1.72, radius: 23, damage: 2, imageKey: 'enemyLemonShockTurretPhoto', statusEffect: 'paralyze', statusChance: 0.62 },
  { id: 'photo-grape-curse-idol', name: 'Photo Grape Curse Idol', bodyColor: 0x7c3aed, accentColor: 0xf0abfc, coreColor: 0x030712, shape: 'mask', hpScale: 2.18, radius: 24, damage: 3, imageKey: 'enemyGrapeCurseIdolPhoto', statusEffect: 'curse', statusChance: 0.68 },
  { id: 'photo-kiwi-frost-wheel', name: 'Photo Kiwi Frost Wheel', bodyColor: 0x84cc16, accentColor: 0xbfdbfe, coreColor: 0x1a2e05, shape: 'spider', hpScale: 1.45, radius: 22, damage: 2, imageKey: 'enemyKiwiFrostWheelPhoto', statusEffect: 'freeze', statusChance: 0.58 },
];

const PHOTO_ENEMY_IMAGE_KEYS = [
  'enemyStrawberryImp',
  'enemyFrostLens',
  'enemyBrassBeetle',
  'enemyVioletMoth',
  'enemyToxicVial',
  'enemyShockCoil',
  'enemyHexMirror',
  'enemyFrostChain',
  'enemyRustBomb',
  'enemyNeonRazor',
  'enemyPrismJaw',
  'enemyJetNeedle',
  'enemyAmberGear',
  'enemyCrimsonShell',
  'enemyBerryDronePhoto',
  'enemyIceLensPhoto',
  'enemyBrassScarabPhoto',
  'enemyToxicVialPhoto',
  'enemyNeonRazorPhoto',
  'enemyHexMirrorPhoto',
  'enemyBerryBrutePhoto',
  'enemyCrystalLensPhoto',
  'enemyGoldScarabPhoto',
  'enemyVioletStingerPhoto',
  'enemyChromeBerryMantisPhoto',
  'enemyCandyCoreDronePhoto',
  'enemyRubyForkDronePhoto',
  'enemyIceSpoonHarrierPhoto',
  'enemyPepperGearIdolPhoto',
  'enemyStrawberryBladeDronePhoto',
  'enemyLemonShockTurretPhoto',
  'enemyGrapeCurseIdolPhoto',
  'enemyKiwiFrostWheelPhoto',
];

function withPhotoImage(variant: EnemyVariant, index: number): EnemyVariant {
  return {
    ...variant,
    imageKey: variant.imageKey ?? PHOTO_ENEMY_IMAGE_KEYS[index % PHOTO_ENEMY_IMAGE_KEYS.length],
  };
}

export function getEnemyVariant(index: number): EnemyVariant {
  return withPhotoImage(ENEMY_VARIANTS[index % ENEMY_VARIANTS.length], index);
}

export function findEnemyVariant(id?: string): EnemyVariant {
  const index = ENEMY_VARIANTS.findIndex((variant) => variant.id === id);
  return index >= 0 ? withPhotoImage(ENEMY_VARIANTS[index], index) : getEnemyVariant(0);
}
